---
# Install dependencies on the host
- name: Install pip
  become: true
  ansible.builtin.apt:
    name: ["python3-dev", "python3-setuptools", "python3-pip",'libopenmpi-dev']
    state: latest
    update_cache: true
  when: ansible_distribution == "Ubuntu"
#sudo apt-get update && sudo apt-get install python3-dev python3-setuptools python-pip

- name: Install pandas
  become: true
  ansible.builtin.pip:
    name: pandas
    state: latest
# pip install --upgrade pip && pip install openstacksdk

- name: Install couchdb
  become: true
  ansible.builtin.pip:
    name: CouchDB
    state: latest


- name: Install screen
  become: yes
  ansible.builtin.package:
    name: screen
    state: present

- name: Install Mpi4py
  become: true
  ansible.builtin.pip:
    name: mpi4py
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install Mastodon.py
  become: true
  ansible.builtin.pip:
    name: Mastodon.py
    state: present
  when: ansible_distribution == "Ubuntu"
#sudo apt-get update && sudo apt-get install python3-dev python3-setuptools python-pip

