- hosts: localhost
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: check-version
    - role: openstack-common
    - role: openstack-images
    - role: openstack-volumes
    - role: openstack-security-groups
    - role: openstack-instances
