---


- name: Kill existing screen session
  ansible.builtin.shell: |
    screen -X -S mpi quit
  ignore_errors: yes


- name: execute harvester via mpi
  ansible.builtin.shell:
    cmd: |
      screen -L -Logfile {{mpi_code_path}}/screen_logfile -dm -S mpi mpiexec -n 2 python3 {{mpi_code_path}}/mpi_run_harvester.py
  async: 10
  # ansible.builtin.shell:
  #   cmd: 
  #       screen -L -Logfile {{mpi_code_path}} -S mpi 
  #       'mpiexec -n 2 python3 "{{ mpi_code_path }}/mpi_run_harvester.py'
  #   #cmd: nohup mpiexec -n 2 python3 "{{ mpi_code_path }}/mpi_run_harvester.py" #> ./output.log 2>&1 &
  # args:
  #   executable: /bin/bash
  # async: 10
  #poll: 0
  #register: mastodon_au_data_result